// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides product recommendations to customers based on their preferences and browsing history.
 *
 * - receiveProductRecommendations - A function that takes customer preferences and browsing history as input and returns a list of recommended product IDs.
 * - ReceiveProductRecommendationsInput - The input type for the receiveProductRecommendations function.
 * - ReceiveProductRecommendationsOutput - The return type for the receiveProductRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ReceiveProductRecommendationsInputSchema = z.object({
  customerPreferences: z
    .string()
    .describe('A description of the customer\u0027s product preferences.'),
  browsingHistory: z
    .string()
    .describe(
      'A description of the customer\u0027s browsing history on the platform.'
    ),
});
export type ReceiveProductRecommendationsInput = z.infer<
  typeof ReceiveProductRecommendationsInputSchema
>;

const ReceiveProductRecommendationsOutputSchema = z.object({
  recommendedProductIds: z
    .array(z.string())
    .describe('An array of product IDs that are recommended for the customer.'),
});
export type ReceiveProductRecommendationsOutput = z.infer<
  typeof ReceiveProductRecommendationsOutputSchema
>;

export async function receiveProductRecommendations(
  input: ReceiveProductRecommendationsInput
): Promise<ReceiveProductRecommendationsOutput> {
  return receiveProductRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'receiveProductRecommendationsPrompt',
  input: {schema: ReceiveProductRecommendationsInputSchema},
  output: {schema: ReceiveProductRecommendationsOutputSchema},
  prompt: `You are an expert recommendation system for an online marketplace called KalaConnect that sells Indian artisan products. Given a customer's preferences and browsing history, you will return a list of recommended product IDs.

Customer Preferences: {{{customerPreferences}}}
Browsing History: {{{browsingHistory}}}

Return only a list of product IDs. Do not include any other explanation. Separate the product IDs with commas.
Example output: ["productId1", "productId2", "productId3"]`,
});

const receiveProductRecommendationsFlow = ai.defineFlow(
  {
    name: 'receiveProductRecommendationsFlow',
    inputSchema: ReceiveProductRecommendationsInputSchema,
    outputSchema: ReceiveProductRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
